/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AppBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "AuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BedrockBasicGuardrailLinkable": {
      "guardrailId": string
      "type": "sst.sst.Linkable"
      "version": string
    }
    "CaddieDatabase": {
      "clusterArn": string
      "database": string
      "host": string
      "password": string
      "port": number
      "reader": string
      "secretArn": string
      "type": "sst.aws.Aurora"
      "username": string
    }
    "CaddieEmail": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "CaddieKnowledgebaseDeletionFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "CaddieKnowledgebaseDeletionQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "CaddieKnowledgebaseIngestionFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "CaddieKnowledgebaseIngestionQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "CaddieKnowledgebaseS3NotificationFifoForwarder": {
      "name": string
      "type": "sst.aws.Function"
    }
    "CaddieKnowledgebaseS3NotificationsQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "CaddieRedis": {
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Redis"
      "username": string
    }
    "CaddieService": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "CaddieVpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "CustomMetadataEndpointKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CustomMetadataEndpointSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "KnowledgebaseDocumentsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "KnowledgebaseStorageBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}